CREATE TABLE account_parameters (
    param_id                VARCHAR(36)   PRIMARY KEY,
    account_id              VARCHAR(36)   NOT NULL UNIQUE REFERENCES account_master(account_id),
    product_id              VARCHAR(36)   NOT NULL REFERENCES account_product(product_id),
    credit_interest_rate    NUMERIC(8,4)  NOT NULL DEFAULT 0,
    debit_interest_rate     NUMERIC(8,4)  NOT NULL DEFAULT 0,
    penalty_rate            NUMERIC(8,4)  NOT NULL DEFAULT 0,
    interest_accrual_freq   VARCHAR(20)   NOT NULL DEFAULT 'DAILY',
    interest_payment_freq   VARCHAR(20)   NOT NULL DEFAULT 'MONTHLY',
    overdraft_limit         NUMERIC(20,2) NOT NULL DEFAULT 0,
    daily_debit_limit       NUMERIC(20,2) NOT NULL DEFAULT 1000000,
    daily_credit_limit      NUMERIC(20,2) NOT NULL DEFAULT 5000000,
    single_txn_limit        NUMERIC(20,2) NOT NULL DEFAULT 500000,
    overdraft_allowed       BOOLEAN       NOT NULL DEFAULT FALSE,
    sweep_enabled           BOOLEAN       NOT NULL DEFAULT FALSE,
    auto_renewal            BOOLEAN       NOT NULL DEFAULT FALSE,
    statements_enabled      BOOLEAN       NOT NULL DEFAULT TRUE,
    statement_day           SMALLINT      NOT NULL DEFAULT 1,
    statement_frequency     VARCHAR(10)   NOT NULL DEFAULT 'MONTHLY',
    special_instruction     VARCHAR(500),
    charge_scheme_ref       VARCHAR(36),
    effective_from          TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_by              VARCHAR(36),
    updated_at              TIMESTAMP,
    version                 INTEGER       NOT NULL DEFAULT 1
);
